CREATE DATABASE THEBHYT
USE THEBHYT

CREATE TABLE QUAN (
	MAQUAN CHAR(2) PRIMARY KEY NOT NULL,
	TenQUAN NVARCHAR(20)
)

CREATE TABLE COSO_YTE (
	MACS_YTE CHAR(5) PRIMARY KEY NOT NULL,
	TenCS_YTE NVARCHAR(50),
	MAQUAN CHAR(2)
)

CREATE TABLE THE_BHYTE (
	MATHE_BHYTE CHAR(15) PRIMARY KEY NOT NULL,
	HO NVARCHAR(10),
	TEN NVARCHAR(10),
	NAMSINH DATE,
	MA_DONVI CHAR(7),
	MA_CS_YTE_DK CHAR(5),
	MAQUAN CHAR(2)
)

CREATE TABLE DONVI (
	MA_DONVI CHAR(7) PRIMARY KEY NOT NULL,
	Ten_DONVI NVARCHAR(20),
	MALOAI_DV CHAR(1)
)

CREATE TABLE LOAIDONVI (
	MA_LOAIDONVI CHAR(1) PRIMARY KEY NOT NULL,
	Ten_LOAIDONVI NVARCHAR(20)
)

alter table COSO_YTE 
	add constraint FK_Q_CSYT foreign key (MAQUAN) references QUAN(MAQUAN)

alter table THE_BHYTE 
	add constraint FK_THE_Q foreign key (MAQUAN) references QUAN(MAQUAN)

alter table THE_BHYTE 
	add constraint FK_THE_DV foreign key (MA_DONVI) references DONVI(MA_DONVI)

alter table DONVI
	add constraint FK_LDV_DV foreign key (MALOAI_DV) references LOAIDONVI(MA_LOAIDONVI)
